name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv (with Python 3.13)
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.13'
          cache: false

      - name: Build sdist and wheel with uv
        run: uv build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    name: Publish to PyPI
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pyxjustiz/
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Set up uv (with Python 3.13)
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.13'
          cache: false

      - name: Publish to PyPI with uv
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish dist/* --token "${PYPI_API_TOKEN}"
